# Reading CHGCAR File from VASP

## Libraries

In [2]:
import os
os.getcwd()
os.chdir("/Users/marcelarruda") #Directory definition

# Import Libraries:
import sys 
import numpy as np
## ATTENTION: Download at: https://pypi.org/project/pymatgen/ then use command "pip install pymatgen"
from pymatgen.core import Structure #https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.Structure
from pymatgen.io.vasp.outputs import VolumetricData 
from pymatgen.core.sites import PeriodicSite

## Using pymatgen

In [3]:
chg_file = 'Downloads/CHGCAR_poliet' # File Path
struct = Structure.from_file(filename=chg_file) #https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.Structure
df = struct.as_dataframe() # get dataframe
# Lattice of the structure.
lattice = struct.lattice
# Fractional coordinates as a Nx3 numpy array.
direct = struct.frac_coords
#Eletronic Density 3D Matrix
poscar, data, data_aug = VolumetricData.parse_file(chg_file) # Parsing means analyzing and converting a program into an internal format that a runtime environment can actually run.
chg_dens_3D = data['total'] #here we have the Eletronic Density 3D Matrix

In [4]:
struct.distance_matrix #Returns the distance matrix between all sites in the structure. For periodic structures, this is overwritten to return the nearest image distance.
np.info(struct.distance_matrix)

class:  ndarray
shape:  (120, 120)
strides:  (960, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7fe05e78f000
byteorder:  little
byteswap:  False
type: float64


In [5]:
#struct.sites #all sites

# Calculations

## Cutoff function with a given radius ($r_c$):

In [6]:
from pymatgen.core.sites import PeriodicSite

r_c = 9.0 # Cutoff Radius - the value used in A. Chandrasekaran et al. is 9Å 
site = (10.0,7.0,12.0) # Arbitrary site (cartesian coords) used for searching neighbors (sites)

sites = struct.get_sites_in_sphere(site, r_c) # What are the sites found given that radius
n_sites = len(sites)
PeriodicSite = PeriodicSite(struct.species[0],site,struct.lattice,coords_are_cartesian = True) # Here we creat a PeriodicSite based on the arbitrary site, this is created only to be used on the get_neighbor_list() function
center_indices, points_indices, offset_vectors, distances = struct.get_neighbor_list(r_c,[PeriodicSite]) # Get neighbors given a radius. Returns the center_indices, points_indices, offset_vectors and the distances
print(f"\nCutoff Radius = {r_c} Å")
print(f"\nArbitrary Site = {site}")
print(f"\nNº of sites found = {n_sites}")
print(f"\nDistances from {site}:\n",distances) #print distances
print("\nSites found:")
sites


Cutoff Radius = 9.0 Å

Arbitrary Site = (10.0, 7.0, 12.0)

Nº of sites found = 195

Distances from (10.0, 7.0, 12.0):
 [8.51322928 5.4177887  6.93363494 5.04100673 5.40311441 7.42226255
 7.72518273 7.46794192 8.73889467 6.7498046  4.79866308 8.80214447
 7.68946088 6.40529184 8.53636475 7.73789128 6.40802081 7.97318352
 3.85666064 6.16906341 1.55610426 5.53027568 5.72359946 5.74828536
 5.43349393 6.03579388 5.82641297 6.76405389 4.4146909  6.12723175
 6.91932185 8.45322802 7.26233441 5.85326899 6.7956038  8.38523373
 6.93758906 8.70752538 5.88884739 8.83919262 7.77524056 7.33292357
 4.82959477 8.62828078 7.74808178 6.41355283 4.89523273 7.73463013
 8.20394404 5.52419503 6.96256841 6.37010064 6.61039859 6.53020513
 7.71173439 6.53276629 8.25577778 8.41031267 6.1652749  8.46473145
 7.2190842  6.88674619 6.24860321 5.90991043 5.23525487 8.39225297
 8.26747088 8.31533446 4.84451539 7.32868603 7.49320347 5.42356724
 4.61041423 8.21305423 8.24622374 6.91726196 5.73066724 1.92937305
 7.295914

[PeriodicSite: H (9.7276, 0.7226, 6.2559) [0.3823, 0.0562, 0.6110],
 PeriodicSite: C (9.5981, 1.7291, 13.1868) [0.3772, 0.1345, 1.2880],
 PeriodicSite: C (9.7123, 0.2971, 13.7505) [0.3817, 0.0231, 1.3430],
 PeriodicSite: H (9.3311, 2.4167, 13.9894) [0.3667, 0.1880, 1.3664],
 PeriodicSite: H (8.7589, 1.7643, 12.4910) [0.3443, 0.1372, 1.2200],
 PeriodicSite: H (8.7653, 0.0257, 14.2192) [0.3445, 0.0020, 1.3888],
 PeriodicSite: H (9.7276, 0.7226, 16.4943) [0.3823, 0.0562, 1.6110],
 PeriodicSite: H (9.8372, -0.4082, 12.9283) [0.3866, -0.0317, 1.2627],
 PeriodicSite: H (9.7276, 13.5802, 6.2559) [0.3823, 1.0562, 0.6110],
 PeriodicSite: H (9.1693, 8.0368, 5.3822) [0.3604, 0.6251, 0.5257],
 PeriodicSite: H (9.9896, 8.9486, 7.6148) [0.3926, 0.6960, 0.7438],
 PeriodicSite: H (9.4525, 7.0910, 3.2154) [0.3715, 0.5515, 0.3140],
 PeriodicSite: C (9.5981, 14.5867, 13.1868) [0.3772, 1.1345, 1.2880],
 PeriodicSite: C (9.7123, 13.1547, 13.7505) [0.3817, 1.0231, 1.3430],
 PeriodicSite: H (9.3311, 15.2743,

## Varying widths (${\sigma_k}$)

- $\sigma_k$ é largura da $k$-éssima gaussiana, cujo valor é definido arbitrariamente. Ou seja, escolheremos o valor que desejarmos para as larguras das gaussianas. Você deve definir o valor desta variável.

- As distâncias entre um ponto específico do grid $g$ e o $i$-éssimo átomo/sítio é dada por $r_{gi}$. Para um dado ponto do grid $g$ (digamos para $g=3$, o terceiro ponto no grid), você pode considerar o vetor (array 1D) $\vec{r_g}$, que terá $N$ elementos, onde $N$ vai ser o número de átomos dentro do raio de corte para ponto do grid $g$. Ou seja, $\vec{r_g}$ terá $N$ elementos $r_{gi}$ onde $i=1,...,N$.

-  $\vec{r}_g$ deve receber as distâncias, e ``` var_width ``` ($\sigma_k$) tem que ser definido com um valor qualquer, 2.5 ou 3.0 por exemplo.

- Maybe we can use ```random.uniform()```  to get a random number between 0 and the $r_c$


In [7]:
#import random
#random.uniform(0, radius)
# Varying widths (σk) - Arbitrary
var_width = 2.5 
r_g = distances

print(f"\nVarying width (σk) = {var_width}")
print(f"\nr_g = {r_g}")


Varying width (σk) = 2.5

r_g = [8.51322928 5.4177887  6.93363494 5.04100673 5.40311441 7.42226255
 7.72518273 7.46794192 8.73889467 6.7498046  4.79866308 8.80214447
 7.68946088 6.40529184 8.53636475 7.73789128 6.40802081 7.97318352
 3.85666064 6.16906341 1.55610426 5.53027568 5.72359946 5.74828536
 5.43349393 6.03579388 5.82641297 6.76405389 4.4146909  6.12723175
 6.91932185 8.45322802 7.26233441 5.85326899 6.7956038  8.38523373
 6.93758906 8.70752538 5.88884739 8.83919262 7.77524056 7.33292357
 4.82959477 8.62828078 7.74808178 6.41355283 4.89523273 7.73463013
 8.20394404 5.52419503 6.96256841 6.37010064 6.61039859 6.53020513
 7.71173439 6.53276629 8.25577778 8.41031267 6.1652749  8.46473145
 7.2190842  6.88674619 6.24860321 5.90991043 5.23525487 8.39225297
 8.26747088 8.31533446 4.84451539 7.32868603 7.49320347 5.42356724
 4.61041423 8.21305423 8.24622374 6.91726196 5.73066724 1.92937305
 7.29591476 6.8136906  4.70696005 2.74342903 7.96668252 7.98888539
 8.88615849 6.32225949 4.9238

## The coefficient $C_k$ is the normalization constant for the Gaussian $k$ and is given by:
$$ C_k = {{1} \over {{2\pi}^{3/2}*\sigma_k^{3} }} $$

- O coeficiente de normalização $C_k$ precisa ser um escalar (valor único) para uma gaussiana específica $k$. Como poderemos ter mais de uma gaussiana no futuro, você pode guardar os coeficientes de normalização num array-1D/vetor $\vec{C}$ se quiser. Veja que agora estamos tentando replicar o trabalho do artigo apenas para uma única gaussiana por enquanto, então não é necessário colocar num vetor (mais pra frente será).

In [8]:
Ck = 1/(((2*np.pi)**(3/2))*(var_width**3))
print(f"\nCk = {Ck}")


Ck = 0.004063592699791422


## Similarly, the components of the vector and tensor fingerprint are given by:

$$ S_k = C_k  \sum \limits _{i=1} ^{i=N} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) $$

$$ V_k^{\alpha} = C_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}}{2\sigma_k^{2}} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) =  S_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}}{2\sigma_k^{2}}$$

$$ T_k^{\alpha \beta} = C_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}r_{gi}^{\beta}}{4\sigma_k^{4}} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) = S_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}r_{gi}^{\beta}}{4\sigma_k^{4}}$$

where, $\alpha$ and $\beta$ represent the $x$, $y$, or $z$ directions.

- Para uma gaussiana específica $k$:

> *    $S_k$ tem que ser um escalar;
> *    $\vec{V}_k$ tem que ser um vetor (array 1D) com 3 elementos: $V_k^{\alpha}$ onde $\alpha=x,y,z$.
> *    $\mathbf{T}_k$ tem que ser uma matriz (array 2D) 3x3 com 9 elementos: $T_k^{\alpha \beta}$ onde $\alpha=x,y,z$, e $\beta=x,y,z$.


### The scalar fingerprint ($S_k$)

$$ S_k = C_k  \sum \limits _{i=1} ^{i=N} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) $$

for a particular grid-point, $g$, and Gaussian, $k$, in an N-atom, single-elemental system


In [9]:
Sk_fingerprint = np.zeros(n_sites)

for i in range(0,n_sites):
    Sk = Ck*np.exp((-r_g[i]**2)/(2*var_width**2))
    #print(Sk)
    Sk_fingerprint[i] = Sk
    #print(Sk_fingerprint)
    
#np.sum(np.ones(10))
Sk_fingerprint = np.sum(Sk_fingerprint)      
print("Scalar fingerprint:\n",Sk_fingerprint)

Scalar fingerprint:
 0.0654047111760892


### Vector Fingerprint ($\vec{V}_k$) 

$$ S_k = C_k  \sum \limits _{i=1} ^{i=N} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) $$

$$ V_k^{\alpha} = C_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}}{2\sigma_k^{2}} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) =  S_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}}{2\sigma_k^{2}}$$

where, $\alpha$ represent the $x$, $y$, or $z$ directions.

> *    $\vec{V}_k$ tem que ser um vetor (array 1D) com 3 elementos: $V_k^{\alpha}$ onde $\alpha=x,y,z$.
>
> $$\vec{V}_k =
\begin{bmatrix}
    {V}_k^{x} & {V}_k^{y} & {V}_k^{z}
\end{bmatrix}
$$

In [10]:
alpha_coords = np.zeros(shape=(3,n_sites))

for i in range(0,n_sites):
    coords = sites[i].coords
    #print(coords)
    alpha_coords[:,i] = coords
    #print(alpha_dist.T)
    
alpha_coords = alpha_coords.T
print(f"\nCoordenates of found sites in x, y and z: \n{alpha_coords}")
site


Coordenates of found sites in x, y and z: 
[[ 9.7275593   0.72259712  6.25586717]
 [ 9.59805188  1.72909005 13.18675205]
 [ 9.7122932   0.29713914 13.75047835]
 [ 9.33114956  2.4167145  13.98944261]
 [ 8.75892522  1.76431987 12.49095038]
 [ 8.76528609  0.0257152  14.2191923 ]
 [ 9.7275593   0.72259712 16.49426717]
 [ 9.83722079 -0.4082288  12.92833483]
 [ 9.7275593  13.58019712  6.25586717]
 [ 9.16932889  8.03677146  5.3822245 ]
 [ 9.98962736  8.94863245  7.61481   ]
 [ 9.45251506  7.0909664   3.21536952]
 [ 9.59805188 14.58669005 13.18675205]
 [ 9.7122932  13.15473914 13.75047835]
 [ 9.33114956 15.2743145  13.98944261]
 [ 8.75892522 14.62191987 12.49095038]
 [ 8.76528609 12.8833152  14.2191923 ]
 [ 9.7275593  13.58019712 16.49426717]
 [ 9.16932889  8.03677146 15.6206245 ]
 [ 9.98962736  8.94863245 17.85321   ]
 [ 9.45251506  7.0909664  13.45376952]
 [ 9.83722079 12.4493712  12.92833483]
 [12.41388414  2.04782995 10.44798005]
 [11.24017544  1.4395369  11.23449394]
 [15.07044008  5.301

(10.0, 7.0, 12.0)

In [11]:
#MODULO!!
#x
alpha_x = np.abs(alpha_coords[:,0] - site[0])
#y
alpha_y = np.abs(alpha_coords[:,1] - site[1])
#z
alpha_z = np.abs(alpha_coords[:,2] - site[2])

In [12]:
Sk = Sk_fingerprint

#X
Vk_fingerprint_x = np.zeros(n_sites)

for i in range(0,n_sites):
    Vk_x = Sk*(alpha_x[i])/(2*var_width**2)
    Vk_fingerprint_x[i] = Vk_x   
Vk_fingerprint_x = np.sum(Vk_fingerprint_x)
print("\nVector fingerprint x:\n",Vk_fingerprint_x)

#Y
Vk_fingerprint_y = np.zeros(n_sites)

for i in range(0,n_sites):
    Vk_y = Sk*(alpha_y[i])/(2*var_width**2)
    Vk_fingerprint_y[i] = Vk_y  
    
Vk_fingerprint_y = np.sum(Vk_fingerprint_y)
print("\nVector fingerprint y:\n",Vk_fingerprint_y)

#Z
Vk_fingerprint_z = np.zeros(n_sites)

for i in range(0,n_sites):
    Vk_z = Sk*(alpha_z[i])/(2*var_width**2)
    Vk_fingerprint_z[i] = Vk_z
    
Vk_fingerprint_z = np.sum(Vk_fingerprint_z)
print("\nVector fingerprint z:\n",Vk_fingerprint_z)

# Vk fingerprint
Vk = [Vk_fingerprint_x, Vk_fingerprint_y, Vk_fingerprint_z]
print("\nVector fingerprint:\n",Vk)


Vector fingerprint x:
 2.8251942263550918

Vector fingerprint y:
 3.916329582593641

Vector fingerprint z:
 3.500530696100361

Vector fingerprint:
 [2.8251942263550918, 3.916329582593641, 3.500530696100361]


### Tensor Fingerprint ($\mathbf{T}_k$)

$$ T_k^{\alpha \beta} = C_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}r_{gi}^{\beta}}{4\sigma_k^{4}} exp \Bigg( \frac {-r_{gi}^{2}}{2\sigma_k^{2}}\Bigg) = S_k  \sum \limits _{i=1} ^{i=N} \frac {r_{gi}^{\alpha}r_{gi}^{\beta}}{4\sigma_k^{4}}$$

where, $\alpha$ and $\beta$ represent the $x$, $y$, or $z$ directions.

> *    $\mathbf{T}_k$ tem que ser uma matriz (array 2D) 3x3 com 9 elementos: $T_k^{\alpha \beta}$ onde $\alpha=x,y,z$, e $\beta=x,y,z$.
>
> $$T_k^{\alpha \beta} =
\begin{bmatrix}
    xx & xy & xz\\
    yx & yy & yz\\
    zx & zy & zz
\end{bmatrix}
$$

In [13]:
beta_x = alpha_x
beta_y = alpha_y
beta_z = alpha_z

In [14]:
#XX ==========================================================
Tk_fingerprint_xx = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_xx = Sk* ((alpha_x[i])*(beta_x[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_xx)
        Tk_fingerprint_xx[i,j] = Tk_xx  
        #print(Tk_fingerprint_xx)
Tk_fingerprint_xx = np.sum(Tk_fingerprint_xx)
print("\nTensor fingerprint xx:\n",Tk_fingerprint_xx)

#XY ==========================================================
Tk_fingerprint_xy = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_xy = Sk* ((alpha_x[i])*(beta_y[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_xy)
        Tk_fingerprint_xy[i,j] = Tk_xy  
        #print(Tk_fingerprint_xy)
Tk_fingerprint_xy = np.sum(Tk_fingerprint_xy)
print("\nTensor fingerprint xy:\n",Tk_fingerprint_xy)

#XZ ==========================================================
Tk_fingerprint_xz = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_xz = Sk* ((alpha_x[i])*(beta_z[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_xz)
        Tk_fingerprint_xz[i,j] = Tk_xz  
        #print(Tk_fingerprint_xz)
Tk_fingerprint_xz = np.sum(Tk_fingerprint_xz)
print("\nTensor fingerprint xz:\n",Tk_fingerprint_xz)

#YX ==========================================================
Tk_fingerprint_yx = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_yx = Sk* ((alpha_y[i])*(beta_x[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_yx)
        Tk_fingerprint_yx[i,j] = Tk_yx  
        #print(Tk_fingerprint_yx)
Tk_fingerprint_yx = np.sum(Tk_fingerprint_yx)
print("\nTensor fingerprint yx:\n",Tk_fingerprint_yx)

#YY ==========================================================
Tk_fingerprint_yy = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_yy = Sk* ((alpha_y[i])*(beta_y[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_yy)
        Tk_fingerprint_yy[i,j] = Tk_yy  
        #print(Tk_fingerprint_yy)
Tk_fingerprint_yy = np.sum(Tk_fingerprint_yy)
print("\nTensor fingerprint yy:\n",Tk_fingerprint_yy)

#YZ ==========================================================
Tk_fingerprint_yz = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_yz = Sk* ((alpha_y[i])*(beta_z[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_yz)
        Tk_fingerprint_yz[i,j] = Tk_yz  
        #print(Tk_fingerprint_yz)
Tk_fingerprint_yz = np.sum(Tk_fingerprint_yz)
print("\nTensor fingerprint yz:\n",Tk_fingerprint_yz)

#ZX ==========================================================
Tk_fingerprint_zx = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_zx = Sk* ((alpha_z[i])*(beta_x[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_zx)
        Tk_fingerprint_zx[i,j] = Tk_zx  
        #print(Tk_fingerprint_zx)
Tk_fingerprint_zx = np.sum(Tk_fingerprint_zx)
print("\nTensor fingerprint zx:\n",Tk_fingerprint_zx)

#ZY ==========================================================
Tk_fingerprint_zy = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_zy = Sk* ((alpha_z[i])*(beta_y[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_zy)
        Tk_fingerprint_zy[i,j] = Tk_zy  
        #print(Tk_fingerprint_zy)
Tk_fingerprint_zy = np.sum(Tk_fingerprint_zy)
print("\nTensor fingerprint zy:\n",Tk_fingerprint_zy)

#ZZ ==========================================================
Tk_fingerprint_zz = np.zeros(shape=(n_sites,n_sites))

for i in range(0,n_sites):
    for j in range(0,n_sites):
        Tk_zz = Sk* ((alpha_z[i])*(beta_z[j]))/(4*var_width**4)
        #print(i,j)
        #print(Tk_zz)
        Tk_fingerprint_zz[i,j] = Tk_zz  
        #print(Tk_fingerprint_zz)
Tk_fingerprint_zz = np.sum(Tk_fingerprint_zz)
print("\nTensor fingerprint zz:\n",Tk_fingerprint_zz)

# Tk fingerprint
Tk = [[Tk_fingerprint_xx, Tk_fingerprint_xy, Tk_fingerprint_xz],
     [Tk_fingerprint_yx, Tk_fingerprint_yy, Tk_fingerprint_yz],
     [Tk_fingerprint_zx, Tk_fingerprint_zy, Tk_fingerprint_zz]]
print("\nTensor fingerprint:\n")
Tk



Tensor fingerprint xx:
 122.03589425142394

Tensor fingerprint xy:
 169.16811535882366

Tensor fingerprint xz:
 151.20744261335415

Tensor fingerprint yx:
 169.16811535882368

Tensor fingerprint yy:
 234.50355675762466

Tensor fingerprint yz:
 209.6061839185493

Tensor fingerprint zx:
 151.20744261335412

Tensor fingerprint zy:
 209.60618391854933

Tensor fingerprint zz:
 187.35217897912858

Tensor fingerprint:



[[122.03589425142394, 169.16811535882366, 151.20744261335415],
 [169.16811535882368, 234.50355675762466, 209.6061839185493],
 [151.20744261335412, 209.60618391854933, 187.35217897912858]]

In [15]:
print(f"\nSk = {Sk}")
print(f"\nVk = {Vk}")
print(f"\nTk = {Tk}")


Sk = 0.0654047111760892

Vk = [2.8251942263550918, 3.916329582593641, 3.500530696100361]

Tk = [[122.03589425142394, 169.16811535882366, 151.20744261335415], [169.16811535882368, 234.50355675762466, 209.6061839185493], [151.20744261335412, 209.60618391854933, 187.35217897912858]]
